version: "2.1"

services:
  ecommerce:
    volumes:
      - ${BITBUCKET_CLONE_DIR}/ecommerce:/edx/app/ecommerce/ecommerce
      - ${BITBUCKET_CLONE_DIR}/ecommerce_node_modules:/edx/app/ecommerce/ecommerce/node_modules
      - ${BITBUCKET_CLONE_DIR}/src:/edx/src
  lms:
    volumes:
      - ${BITBUCKET_CLONE_DIR}/edx-platform:/edx/app/edxapp/edx-platform
      - ${BITBUCKET_CLONE_DIR}/edxapp_node_modules:/edx/app/edxapp/edx-platform/node_modules
      - ${BITBUCKET_CLONE_DIR}/src:/edx/src
  edx_notes_api:
    volumes:
      - ${BITBUCKET_CLONE_DIR}/edx-notes-api:/edx/app/edx_notes_api/edx_notes_api
      - ${BITBUCKET_CLONE_DIR}/src:/edx/src
  studio:
    volumes:
      - ${BITBUCKET_CLONE_DIR}/edx-platform:/edx/app/edxapp/edx-platform
      - ${BITBUCKET_CLONE_DIR}/edxapp_node_modules:/edx/app/edxapp/edx-platform/node_modules
      - ${BITBUCKET_CLONE_DIR}/src:/edx/src
 
      
volumes:
  edxapp_node_modules:
